[package]
name = "todoapp"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.2"
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
itertools = "0.13.0"
chrono = "0.4.38"
