[package]
name = "todoapp"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
itertools = "0.14.0"
chrono = {version = "0.4.38", features = ["serde"]}
